spring:
  application:
    name: transaction-service

  webhook:
    url: "http://localhost:8081/api/v1/retail/orders/webhook"

  jackson:
    property-naming-strategy: SNAKE_CASE

# Tomcat configuration
server:
  port: 8082
